---
ScenarioDuration: 300
ScenarioModules:
  - Voltage:
      - endval: 33000
        duration: 300
    Temperature:
      - endval: 33
        duration: 120
      - endval: 32
        duration: 180
    TxPower:
      - endval: -1000
        duration: 300
    RxPower:
      - endval: -1100
        duration: 120
      - endval: -3850
        duration: 1
      - endval: -3850
        duration: 179
    Osnr:
      - endval: 230
        duration: 120
      - endval: 0
        duration: 1
      - endval: 0
        duration: 179
  
  - Voltage:
      - endval: 33000
        duration: 300
    Temperature:
      - endval: 31
        duration: 300
    TxPower:
      - endval: -1000
        duration: 300
    RxPower:
      - endval: -1100
        duration: 120
      - endval: -3850
        duration: 1
      - endval: -3850
        duration: 179
    Osnr:
      - endval: 230
        duration: 120
      - endval: 0
        duration: 1
      - endval: 0
        duration: 179
...