---
ScenarioDuration: 300
ScenarioModules:
  - Voltage: # in mV
      - endval: 33000
        duration: 300
    Temperature: # in 0.1 C's degrees
      - endval: 330
        duration: 120
      - endval: 320
        duration: 180
    TxPower: # in 0.01 dBm
      - endval: -1000
        duration: 300
    RxPower: # in 0.01 dBm
      - endval: -1100
        duration: 120
      - endval: -3850
        duration: 1
      - endval: -3850
        duration: 179
    Osnr: # in 0.1 dB
      - endval: 230
        duration: 120
      - endval: 0
        duration: 1
      - endval: 0
        duration: 179
  
  - Voltage:
      - endval: 33000
        duration: 300
    Temperature:
      - endval: 310
        duration: 300
    TxPower:
      - endval: -1000
        duration: 300
    RxPower:
      - endval: -1100
        duration: 120
      - endval: -3850
        duration: 1
      - endval: -3850
        duration: 179
    Osnr:
      - endval: 230
        duration: 120
      - endval: 0
        duration: 1
      - endval: 0
        duration: 179
...