---
Modules:
  ## Module 1
  # Lower Page
- SFF8024Identifier: 0x18 # https://www.snia.org/technology-communities/sff/specifications
  CmisRevision: 0x50
  ModuleRevision: 0x1000 # 0x<major>00 + 0x<minor> revisions
  MediaType: 0x02 # CMIS P116, T8-16
  # Page 00h
  VendorName: FibreFiberLtd
  DateCode: 2022-08-25  # production date
  MaxPower: 0x50  # U8 max power consumption (multiplied by 0.25W)
  # Page 01h
  LenghtSMF: 120 # in kilometers
  ModuleTempMax: 60 # in Celsius degrees
  ModuleTempMin: 0
  # Page 02h
  TempMonHighWarningThreshold: 75
  TempMonLowWarningThreshold: 15
  VccMonHighWarningThreshold: 34320 # in 0.1 mV
  VccMonLowWarningThreshold: 31680
  OpticalPowerTxHighWarningThreshold: 6309 # in 0.1 uW
  OpticalPowerTxLowWarningThreshold: 251
  LaserBiasCurrentHighWarningThreshold: 0 #?
  LaserBiasCurrentLowWarningThreshold: 0 #?
  OpticalPowerRxHighWarningThreshold: 10000 # in 0.1 uW
  OpticalPowerRxLowWarningThreshold: 100
  # Page 04h
  ProgOutputPowerMin: -2290 # in 0.01 dBm
  ProgOutputPowerMax: 400
  # Page 12h
  GridSpacingTxx: 0x50 # CMIS P173, T8-65
  CurrentLaserFrequencyTxx: 193100000 # in MHz
  TargetOutputPowerTxx: -1250 # in 0.01 dBm

## Module 2
# Lower Page
- SFF8024Identifier: 0x18 # https://www.snia.org/technology-communities/sff/specifications
  CmisRevision: 0x50
  ModuleRevision: 0x1000 # 0x<major>00 + 0x<minor> revisions
  MediaType: 0x02 # CMIS P116, T8-16
  # Page 00h
  VendorName: FibreFiberLtd
  DateCode: 2022-08-25  # production date
  MaxPower: 0x50  # U8 max power consumption (multiplied by 0.25W)
  # Page 01h
  LenghtSMF: 120 # in kilometers
  ModuleTempMax: 60 # in Celsius degrees
  ModuleTempMin: 0
  # Page 02h
  TempMonHighWarningThreshold: 75
  TempMonLowWarningThreshold: 15
  VccMonHighWarningThreshold: 34320 # in 0.1 mV
  VccMonLowWarningThreshold: 31680
  OpticalPowerTxHighWarningThreshold: 6309 # in 0.1 uW
  OpticalPowerTxLowWarningThreshold: 251
  LaserBiasCurrentHighWarningThreshold: 0 #?
  LaserBiasCurrentLowWarningThreshold: 0 #?
  OpticalPowerRxHighWarningThreshold: 10000 # in 0.1 uW
  OpticalPowerRxLowWarningThreshold: 100
  # Page 04h
  ProgOutputPowerMin: -2290 # in 0.01 dBm
  ProgOutputPowerMax: 400
  # Page 12h
  GridSpacingTxx: 0x50 # CMIS P173, T8-65
  CurrentLaserFrequencyTxx: 193100000 # in MHz
  TargetOutputPowerTxx: -1250 # in 0.01 dBm
...